### ISSUE TITLE
Using this.el on view's events

### ISSUE THREAD

**Issue by brunograsselli** [andremendonca/dronejs#5]
Hey guys,

When declaring events, like:

var MainView = Drone.View({
  events: {
    ".add_new_product": {"click": "bindAddNewProduct"}
  }
...

It should look for the object based on this.el element.

What do you, guys, think?

**Comment by renatonitta** [comment]
I don't see the need of this, but still makes sense to me.

Do you have any specific scenario that needs it?

**Comment by brunograsselli** [comment]
Yes, every time I use this.el I can't use the events syntax.

Imagine you have some buttons on your page and you have a view for each button. So you wanna bind this button click to some function. You can't use the event syntax cause you don't know which is your button, you have this.el exactly for that (this.el.bind("click", someFunction)).

And another point, your view should not see an element outside this.el, so you can always look for elements inside this.el (when trying to bind events).

**Comment by renatonitta** [comment]
Now I see the need of this. :+1:

**Comment by andremendonca** [comment]
Good discussion, I also agree with you guys, we should see it soon ;).

PS: @renatocn, @BrunoGrasselli is crying and jumping right now because you agreed! lol
